## Afiliados Seguridad Social 2011
En este notebook procesaremos un .xlsx con el número de afiliados por municipios, dentro del régimen general, agrario, hogar, mar, autónomos, carbón y una última columna con el total.  
Obtendremos un DataFrame con la siguiente información:
- Codigo Municipio
- Regimen General
- Regimen Agrario
- Regimen Hogar
- Regimen Mar
- Regimen Autonomos
- Regimen Carbon
- Total Regimen SS

In [1]:
import pandas as pd

In [2]:
AfiliadosSS11 = pd.read_excel('06_Input_Afiliados_SS_11.xlsx',dtype='object')
AfiliadosSS11.head()

,PROVINCIA,CODIGO,MUNICIPIO,TRAB,GENERAL,AGRARIO,MAR,HOGAR,AUTONOMOS,CARBON,TOTAL
0,01 ALAVA,01001,ALEGRIA-DULANTZI,TRAB.,637,<5,0,8,186,0,832
1,01 ALAVA,01002,AMURRIO,TRAB.,3836,14,0,46,622,0,4518
2,01 ALAVA,01003,ARAMAIO,TRAB.,116,<5,0,<5,73,0,196
3,01 ALAVA,01004,ARTZINIEGA,TRAB.,297,6,0,<5,105,0,412
4,01 ALAVA,01006,ARMIÑON,TRAB.,121,0,0,0,21,0,142

In [3]:
AfiliadosSS11.drop(['PROVINCIA', 'MUNICIPIO', 'TRAB', 'TOTAL'], axis = 1, inplace = True)
AfiliadosSS11.rename({'CODIGO' : 'Codigo Municipio',
                      'GENERAL': 'Regimen General',
                      'AGRARIO': 'Regimen Agrario', 
                      'HOGAR' : 'Regimen Hogar', 
                      'MAR' : 'Regimen Mar', 
                      'AUTONOMOS' : 'Regimen Autonomos', 
                      'CARBON' : 'Regimen Carbon'}, axis = 1, inplace = True)
AfiliadosSS11.head()

,Codigo Municipio,Regimen General,Regimen Agrario,Regimen Mar,Regimen Hogar,Regimen Autonomos,Regimen Carbon
0,01001,637,<5,0,8,186,0
1,01002,3836,14,0,46,622,0
2,01003,116,<5,0,<5,73,0
3,01004,297,6,0,<5,105,0
4,01006,121,0,0,0,21,0

Los valores que están entre 0 y 5 se indican en la tabla con <5. Substituimos estos valores por un 2.  
Ademá creamos una nueva columna con la suma de todas las columnas segun régimen.

In [4]:
AfiliadosSS11.dtypes

Codigo Municipio     object
Regimen General      object
Regimen Agrario      object
Regimen Mar          object
Regimen Hogar        object
Regimen Autonomos    object
Regimen Carbon       object
dtype: object

In [5]:
AfiliadosSS11 = AfiliadosSS11.applymap(lambda x: 2 if x == '<5' else x)

In [6]:
AfiliadosSS11[['Regimen General', 'Regimen Agrario','Regimen Hogar', 'Regimen Mar','Regimen Autonomos', 'Regimen Carbon']] = AfiliadosSS11[['Regimen General', 
                                                                                                                                            'Regimen Agrario',
                                                                                                                                            'Regimen Hogar', 
                                                                                                                                            'Regimen Mar', 
                                                                                                                                            'Regimen Autonomos', 
                                                                                                                                            'Regimen Carbon']].astype(int)

In [7]:
AfiliadosSS11['Total Regimen SS'] = AfiliadosSS11['Regimen General'] + AfiliadosSS11['Regimen Agrario'] + AfiliadosSS11['Regimen Hogar'] + AfiliadosSS11['Regimen Mar'] + AfiliadosSS11['Regimen Autonomos'] + AfiliadosSS11['Regimen Carbon']

In [8]:
AfiliadosSS11.head()

,Codigo Municipio,Regimen General,Regimen Agrario,Regimen Mar,Regimen Hogar,Regimen Autonomos,Regimen Carbon,Total Regimen SS
0,01001,637,2,0,8,186,0,833
1,01002,3836,14,0,46,622,0,4518
2,01003,116,2,0,2,73,0,193
3,01004,297,6,0,2,105,0,410
4,01006,121,0,0,0,21,0,142

In [9]:
AfiliadosSS11.to_csv('06_Output_Afiliados_SS_11.csv', header = True, index = False)