## Contratos laborales 2011

En este notebook procesaremos un .xls con el número de contratos laborales por municipios, por tipo de contrato; temporal e indefinido, por sexo, y por sector; agricultura, industria, construcción y servicios.  

Obtendremos un DataFrame con la siguiente información:
- Codigo Municipio
- Total Contratos
- Contratos iniciales indefinidos hombres
- Contratos iniciales temporales hombres
- Contratos convertidos en indefinidos hombres
- Contratos iniciales indefinidos mujeres
- Contratos iniciales temporales mujeres
- Contratos convertidos en indefinidos mujeres
- Contratos  Agricultura
- Contratos  Industria
- Contratos Construcción
- Contratos  Servicios

In [1]:
import pandas as pd

In [2]:
ContratosLaborales11 = pd.read_excel('07_Input_Contratos_Laborales_11.xls',dtype='object')
ContratosLaborales11.head()

,Año,Código de CA,Comunidad Autónoma,Codigo Provincia,Provincia,Codigo Municipio,Municipio,Total Contratos,Contratos iniciales indefinidos hombres,Contratos iniciales temporales hombres,Contratos convertidos en indefinidos hombres,Contratos iniciales indefinidos mujeres,Contratos iniciales temporales mujeres,Contratos convertidos en indefinidos mujeres,Contratos Agricultura,Contratos Industria,Contratos Construcción,Contratos Servicios
0,2010,16,País Vasco,1,Araba/Álava,01001,Alegría-Dulantzi,31,0,24,0,0,7,0,0,3,13,15
1,2010,16,País Vasco,1,Araba/Álava,01002,Amurrio,382,3,276,15,1,82,5,2,227,14,139
2,2010,16,País Vasco,1,Araba/Álava,01003,Aramaio,6,0,4,0,0,2,0,0,0,0,6
3,2010,16,País Vasco,1,Araba/Álava,01004,Artziniega,9,0,2,1,0,4,2,0,1,1,7
4,2010,16,País Vasco,1,Araba/Álava,01006,Armiñón,3,0,0,0,0,1,2,0,3,0,0

In [3]:
ContratosLaborales11.drop(['Año',
                           'Código de CA', 
                           'Comunidad Autónoma', 
                           'Codigo Provincia', 'Provincia', 
                           ' Municipio'], axis=1, inplace=True)
ContratosLaborales11.head()

,Codigo Municipio,Total Contratos,Contratos iniciales indefinidos hombres,Contratos iniciales temporales hombres,Contratos convertidos en indefinidos hombres,Contratos iniciales indefinidos mujeres,Contratos iniciales temporales mujeres,Contratos convertidos en indefinidos mujeres,Contratos Agricultura,Contratos Industria,Contratos Construcción,Contratos Servicios
0,01001,31,0,24,0,0,7,0,0,3,13,15
1,01002,382,3,276,15,1,82,5,2,227,14,139
2,01003,6,0,4,0,0,2,0,0,0,0,6
3,01004,9,0,2,1,0,4,2,0,1,1,7
4,01006,3,0,0,0,0,1,2,0,3,0,0

In [4]:
ContratosLaborales11.to_csv('07_Output_Contratos_Laborales_11.csv', header = True, index = False)