## Parados 2011
En este notebook procesaremos un .xls que contiene el paro registrado por municipios, sexo, edad; <25, 25-45, >45, y sector de actividad económica; agricultura, industria, construcción, servicios y parados de larga duración.  

Obtendremos un DataFrame con la siguiente información:
- Codigo Municipio
- Paro hombre edad < 25
- Paro hombre edad 25-45
- Paro hombre edad >=45
- Paro mujer edad < 25
- Paro mujer edad 25-45
- Paro mujer edad >=45
- Paro Agricultura
- Paro Industria
- Paro Construcción
- Paro Servicios
- Paro Sin empleo Anterior

In [1]:
import pandas as pd

In [2]:
Parados11 = pd.read_excel('08_Input_Parados_11.xls',dtype='object')
Parados11.head()

,Año,Código de CA,Comunidad Autónoma,Codigo Provincia,Provincia,Codigo Municipio,Municipio,total Paro Registrado,Paro hombre edad < 25,Paro hombre edad 25 -45,Paro hombre edad >=45,Paro mujer edad < 25,Paro mujer edad 25 -45,Paro mujer edad >=45,Paro Agricultura,Paro Industria,Paro Construcción,Paro Servicios,Paro Sin empleo Anterior
0,2010,16,País Vasco,1,Araba/Álava,01001,Alegría-Dulantzi,147,7,44,20,10,50,16,3,30,13,97,4
1,2010,16,País Vasco,1,Araba/Álava,01002,Amurrio,601,31,135,105,31,158,141,9,114,73,384,21
2,2010,16,País Vasco,1,Araba/Álava,01003,Aramaio,30,2,5,11,2,5,5,0,17,0,13,0
3,2010,16,País Vasco,1,Araba/Álava,01004,Artziniega,132,6,34,16,3,48,25,2,23,10,90,7
4,2010,16,País Vasco,1,Araba/Álava,01006,Armiñón,14,1,3,1,0,6,3,0,3,2,9,0

In [3]:
Parados11.drop(['Año',
                'Código de CA', 
                'Comunidad Autónoma', 
                'Codigo Provincia', 
                'Provincia', 
                ' Municipio'], axis=1, inplace=True)
Parados11.head()

,Codigo Municipio,total Paro Registrado,Paro hombre edad < 25,Paro hombre edad 25 -45,Paro hombre edad >=45,Paro mujer edad < 25,Paro mujer edad 25 -45,Paro mujer edad >=45,Paro Agricultura,Paro Industria,Paro Construcción,Paro Servicios,Paro Sin empleo Anterior
0,01001,147,7,44,20,10,50,16,3,30,13,97,4
1,01002,601,31,135,105,31,158,141,9,114,73,384,21
2,01003,30,2,5,11,2,5,5,0,17,0,13,0
3,01004,132,6,34,16,3,48,25,2,23,10,90,7
4,01006,14,1,3,1,0,6,3,0,3,2,9,0

In [4]:
Parados11.to_csv('08_Output_Parados_11.csv', header = True, index = False)