## Número de jubilados y estudiantes 2011
En este notebook procesaremos un .xlsx con el número de personas jubiladas y estudiantes desagregado por municipios.  
Obtendremos un DataFrame con la siguiente información:
- Codigo Municipio
- Nº de Jubilados 	
- Nº de Estudiantes

In [1]:
import pandas as pd

In [2]:
EstudiantesJubilados11 = pd.read_excel('21_Input_Estudiantes_Jubilados_11.xlsx', usecols = ['Municipio de residencia',
                                                                                            'Jubilado/a, prejubilado/a, pensionista o rentista',
                                                                                            'Estudiantes'], dtype='object')
EstudiantesJubilados11.head()

,Municipio de residencia,"Jubilado/a, prejubilado/a, pensionista o rentista",Estudiantes
0,44001 Ababuj,30,*
1,40001 Abades,185,120
2,10001 Abadía,85,55
3,27001 Abadín,1125,190
4,48001 Abadiño,1250,1410

Añadimos el campo Código Municipio al DataFrame asignando el valor de cada fila en función del código que aparece en el campo municipio de residencia.  
Para ello usamos la tabla 01_Output_ProvMun_11.csv que contiene los códigos por municipio:

In [3]:
ProvMun = pd.read_csv('01_Output_ProvMun_11.csv', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia  Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Alegría-Dulantzi            01001
1      Araba/Álava               01           Amurrio            01002
2      Araba/Álava               01             Añana            01049
3      Araba/Álava               01           Aramaio            01003
4      Araba/Álava               01           Armiñón            01006

In [4]:
MunList = ProvMun['Codigo Municipio'].tolist()

In [5]:
def check_list(x):
    for l in MunList:
        if l in x:
            return l
    return ''

In [6]:
EstudiantesJubilados11['Codigo Municipio'] = EstudiantesJubilados11['Municipio de residencia'].map(lambda x: check_list(x))
EstudiantesJubilados11.head()

,Municipio de residencia,"Jubilado/a, prejubilado/a, pensionista o rentista",Estudiantes,Codigo Municipio
0,44001 Ababuj,30,*,44001
1,40001 Abades,185,120,40001
2,10001 Abadía,85,55,10001
3,27001 Abadín,1125,190,27001
4,48001 Abadiño,1250,1410,48001

In [7]:
EstudiantesJubilados11 = EstudiantesJubilados11.drop(['Municipio de residencia'], axis = 1)
EstudiantesJubilados11 = EstudiantesJubilados11.rename({'Jubilado/a, prejubilado/a, pensionista o rentista': 'Nº de Jubilados',
                                                        'Estudiantes' : 'Nº de Estudiantes'}, axis = 1)
PrimeraColumna = EstudiantesJubilados11.pop('Codigo Municipio')
EstudiantesJubilados11.insert(0,'Codigo Municipio', PrimeraColumna)
EstudiantesJubilados11.head()

  Codigo Municipio Nº de Jubilados Nº de Estudiantes
0            44001              30                 *
1            40001             185               120
2            10001              85                55
3            27001            1125               190
4            48001            1250              1410

In [8]:
EstudiantesJubilados11.to_csv('21_Output_Jubliados_Estudiantes_11.csv', header = True, index = False)